<?php
define('TEXT_REZERVARE_ONLINE','Rezervare online');
define('TEXT_DATA_CHECKIN','Data sosirii');
define('TEXT_DATA_CHECKOUT','Data plecare');
define('TEXT_ADULTI_CAMERA','Adulţi/cameră');
define('TEXT_CAUTARE','Căutare');
define('TEXT_ALERTA_DATA_CHECKIN','Vă rugăm să introduceţi data sosirii');
define('TEXT_ALERTA_DATA_CHECKOUT','Vă rugăm să introduceţi data de Check-Out');
define('TEXT_CAUTARE_INTRARI','Căutare intrare');
define('TEXT_CHECKIN_D','Data sosirii');
define('TEXT_CHECKOUT_D','Data plecare');
define('TEXT_TOTAL_NOPTI','Nr. de nopti');
define('TEXT_ADULTI_CAMERA_D','Adulţi/cameră');
define('TEXT_REZULTAT_CAUTARE','Rezultat al căutării');
define('TEXT_ALERTA_SELECTARE_CAMERA','Vă rugăm să selectaţi cel putin o cameră');
define('TEXT_MAX_OCUPARE','Nr. maxim de persoane');
define('SELECT_NUMBER_OF_ROOM_TEXT','Camere dorite');
define('TEXT_ADULTI','Adulţi');
define('TEXT_PRET_TOTAL_CAMERA','Total de preţ / cameră');
define('TEXT_VIZUALIZARE_OFERTE','Vizualizare oferte');
define('TEXT_ASCUNDE_VIZUALIZARE_OFERTE','Ascunde oferte');
define('TEXT_CONTINUARE','Continua');
define('MON','Luni');
define('TUE','Marti');
define('WED','Miercuri');
define('THU','Joi');
define('FRI','Vineri');
define('SAT','Sambata');
define('SUN','Duminica');
define('MONTH','Lună');
define('TEXT_REZERVARI_DETALII','Detaliile rezervarii');
define('TEXT_DATA_CHECK_IN','Data sosirii');
define('TEXT_DATA_CHECK_OUT','Data plecarii');
define('TEXT_NUMAR_NOPTI','Nr. nopti');
define('TEXT_NUMAR_CAMERE','Nr. camere');
define('NUMBER_OF_ROOM_TEXT','Numărul de camere');
define('TEXT_TIPUL_CAMEREI','Tipul camerei');
define('TEXT_NUMAR_MAXIM_OCUPANTI','Nr. maxim de persoane');
define('TEXT_TOTAL_BRUT','Total brut');
define('TEXT_SUBTOTAL','Sub Total');
define('TEXT_TAXE','Fiscale');
define('TEXT_TOTAL_GENERAL','Totalul general');
define('TEXT_PLATI_AVANSATE','Plata în avans');
define('TEXT_DIN_TOTAL_PLATA','din totalul platii general');
define('TEXT_DETALII_CLIENT_I','Detalii client');
define('EXISTING_CUSTOMER_TEXT','Client existent');
define('TEXT_ADRESA_EMAIL','Adresa de e-mail');
define('FETCH_DETAILS_TEXT','Preia detalii');
define('OR_TEXT','SAU');
define('TEXT_CLIENT_NOU','Client nou');
define('TITLU_TEXT','Titlul');
define('TEXT_DOMNUL','D-l');
define('MS_TEXT','MS');
define('TEXT_DOAMNA','D-na');
define('TEXT_DOMNISOARA','D-ra');
define('DR_TEXT','Dr');
define('PROF_TEXT','Prof');
define('TEXT_NUME_FAMILIE','Nume');
define('TEXT_PRENUME','Prenume');
define('TEXT_ADRESA','Adresa');
define('TEXT_ORAS','Oras');
define('TEXT_JUDET','Judet');
define('TEXT_COD_POSTAL','Cod poştal');
define('TEXT_TARA','Ţară');
define('TEXT_TELEFON','Telefon');
define('TEXT_FAX','Fax');
define('TEXT_EMAIL','E-mail');
define('TEXT_PLATA_PRIN','Plata prin');
define('TEXT_ALERTA_CAMP_REQ','Acest câmp este necesar');
define('TEXT_ALTE_CERINTE','Orice solicitări suplimentare');
define('TEXT_SUNT_DE_ACORD',' Sunt de acord cu');
define('TEXT_TERMENI_SI_CONDITII','Termeni & condiţii');
define('TEXT_CONFIRMARE','Confirma');
define('TEXT_VERIFICA_COS_PRODUSE','Verifica cos produse');
define('TEXT_TAXE_FISCALE_INCLUSE','Inclusiv fiscale');
define('TEXT_NUMAR_REZERVARE','Numărul rezervării');
define('TEXT_NUMELE_CLIENTULUI','Numele clientului');
define('TEXT_ADULTI_A','Adulţi');
define('TEXT_DETALII_PLATA_A','Detalii plată');
define('TEXT_OPTIUNI_PLATA_A','Opţiune de plată');
define('TEXT_ID_TRANZACTIE_A','Tranzacţie ID');
define('A_STIMA','Cu stimă');
define('A_CAR','Va trebui să efectueze o imprimare din acest e-mail şi îl prezintă hotelului la sosirea şi de check-in. Acest e-mail este documentul justificativ de confirmare pentru rezervarea dumneavoastră.');
define('DETALII_CARD','Detaliile cardului de credit');
define('DETINATOR_CARD','Numele titularului cardului');
define('TIP_CARD','Tipul de Card de credit');
define('NUMAR_CARTE_CREDIT','Numărul cardului de credit');
define('DATA_EXPIRARE_CARD','Data expirării');
define('SUMA_CARD','Suma totală');
define('TERMENI_1_CARD','Sunt de acord pentru a permite');
define('TERMENI_2_CARD','să deducă');
define('TERMENI_3_CARD','din cartea mea de credit');
define('CC_SUBMIT','Trimite');
define('TEXT_REZERVARE_FINALIZATA','Rezervare completă');
define('TEXT_MULTUMESC','Vă mulţumim pentru rezervarea efectuată!');
define('TEXT_REZERVARE_EFECTUTA_SUCCESS','Rezervarea a fost efectuata cu succes');
define('TEXT_FACUTA_TRIMISA','Ati primit un mail cu factura dumneavoastra. Va multumim.');
define('TEXT_REZERVARE_ESUATA','Rezervare eşuata.');
define('TEXT_EROARE_REZERVARE_1','Acces direct la această pagină este restricţionată.');
define('TEXT_EROARE_REZERVARE_2','Altcineva dobândi deja blocare de rezervare pe camere specificate de dvs. Blocare rezervarea va fi lansat automat după câteva minute pe finalizarea rezervării sau eşecul de o altă persoană. Vă rugăm să modificaţi criteriile de căutare şi încercaţi din nou.');
define('TEXT_EROARE_REZERVARE_3','Metodă de plată nedefinit selectat. Vă rugăm să contactaţi administratorul.');
define('TEXT_EROARE_REZERVARE_4','Trimite e-mail de notificare nu a reușit. Vă rugăm să contactaţi asistenţa tehnică.');
?>